#!/bin/bash
# Example nx wrapper script with Node.js version check
# This would be generated by debian/rules

# Function to check Node.js version
check_node_version() {
    local node_version=$(node -v 2>/dev/null | grep -oE 'v[0-9]+' | cut -c2-)
    
    if [ -z "$node_version" ]; then
        echo "WARNING: Unable to determine Node.js version" >&2
        return
    fi
    
    if [ "$node_version" -lt 20 ]; then
        cat >&2 << 'EOF'
╔══════════════════════════════════════════════════════════════════════╗
║                         ⚠️  NODE.JS WARNING ⚠️                         ║
╠══════════════════════════════════════════════════════════════════════╣
║ You are using Node.js version EOF
        printf "║ %-68s ║\n" "v$node_version" >&2
        cat >&2 << 'EOF'
║ Node.js >= 20 is recommended for optimal compatibility with nx.      ║
║                                                                      ║
║ Your current version may work but could encounter issues.            ║
║                                                                      ║
║ To upgrade Node.js:                                                  ║
║ • Visit: https://nodejs.org/en/download/                             ║
║ • Or use NodeSource: https://github.com/nodesource/distributions    ║
║                                                                      ║
║ For Ubuntu/Debian:                                                   ║
║   curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - ║
║   sudo apt-get install -y nodejs                                     ║
╚══════════════════════════════════════════════════════════════════════╝

EOF
    fi
}

# Check version before running nx
check_node_version

# Run nx with proper NODE_PATH
NODE_PATH="/usr/lib/nx/node_modules" exec node /usr/lib/nx/node_modules/nx/bin/nx.js "$@"