// Auto-generated redirects for Nx recipes migration
// Generated on: 2025-06-02T17:40:35.787Z

const nxRecipesRedirects = {
  "/recipes/module-federation": "/technologies/module-federation",
  "/recipes/module-federation/create-a-host": "/technologies/module-federation/recipes/create-a-host",
  "/recipes/module-federation/create-a-remote": "/technologies/module-federation/recipes/create-a-remote",
  "/recipes/module-federation/federate-a-module": "/technologies/module-federation/recipes/federate-a-module",
  "/recipes/react": "/technologies/react",
  "/recipes/react/react-native": "/technologies/react/recipes/react-native",
  "/recipes/react/remix": "/technologies/react/recipes/remix",
  "/recipes/react/react-router": "/technologies/react/recipes/react-router",
  "/recipes/react/use-environment-variables-in-react": "/technologies/react/recipes/use-environment-variables-in-react",
  "/recipes/react/using-tailwind-css-in-react": "/technologies/react/recipes/using-tailwind-css-in-react",
  "/recipes/react/adding-assets-react": "/technologies/react/recipes/adding-assets-react",
  "/recipes/react/module-federation-with-ssr": "/technologies/angular/recipes/module-federation-with-ssr",
  "/recipes/react/deploy-nextjs-to-vercel": "/technologies/react/recipes/deploy-nextjs-to-vercel",
  "/recipes/react/react-compiler": "/technologies/react/recipes/react-compiler",
  "/recipes/angular": "/technologies/angular",
  "/recipes/angular/rspack": "/technologies/build-tools/rspack",
  "/recipes/angular/rspack/introduction": "/technologies/typescript/introduction",
  "/recipes/angular/rspack/getting-started": "/technologies/angular/angular-rspack/recipes/getting-started",
  "/recipes/angular/rspack/migrate-from-webpack": "/technologies/angular/angular-rspack/recipes/migrate-from-webpack",
  "/recipes/angular/rspack/handling-configurations": "/technologies/angular/angular-rspack/recipes/handling-configurations",
  "/recipes/angular/rspack/internationalization": "/technologies/angular/angular-rspack/recipes/internationalization",
  "/recipes/angular/migration": "/technologies/angular/migration",
  "/recipes/angular/migration/angular": "/technologies/angular",
  "/recipes/angular/migration/angular-multiple": "/technologies/angular/migration/angular-multiple",
  "/recipes/angular/use-environment-variables-in-angular": "/technologies/angular/recipes/use-environment-variables-in-angular",
  "/recipes/angular/using-tailwind-css-with-angular-projects": "/technologies/angular/recipes/using-tailwind-css-with-angular-projects",
  "/recipes/angular/module-federation-with-ssr": "/technologies/angular/recipes/module-federation-with-ssr",
  "/recipes/angular/dynamic-module-federation-with-angular": "/technologies/angular/recipes/dynamic-module-federation-with-angular",
  "/recipes/angular/setup-incremental-builds-angular": "/technologies/angular/recipes/setup-incremental-builds-angular",
  "/recipes/node": "/technologies/node",
  "/recipes/node/node-server-fly-io": "/technologies/node/recipes/node-server-fly-io",
  "/recipes/node/node-serverless-functions-netlify": "/technologies/node/recipes/node-serverless-functions-netlify",
  "/recipes/node/node-aws-lambda": "/technologies/node/recipes/node-aws-lambda",
  "/recipes/node/application-proxies": "/technologies/node/recipes/application-proxies",
  "/recipes/node/wait-for-tasks": "/technologies/node/recipes/wait-for-tasks",
  "/recipes/storybook": "/technologies/test-tools/storybook",
  "/recipes/storybook/overview-react": "/technologies/test-tools/storybook/recipes/overview-react",
  "/recipes/storybook/overview-angular": "/technologies/test-tools/storybook/recipes/overview-angular",
  "/recipes/storybook/overview-vue": "/technologies/test-tools/storybook/recipes/overview-vue",
  "/recipes/storybook/configuring-storybook": "/technologies/test-tools/storybook/recipes/configuring-storybook",
  "/recipes/storybook/one-storybook-for-all": "/technologies/test-tools/storybook/recipes/one-storybook-for-all",
  "/recipes/storybook/one-storybook-per-scope": "/technologies/test-tools/storybook/recipes/one-storybook-per-scope",
  "/recipes/storybook/one-storybook-with-composition": "/technologies/test-tools/storybook/recipes/one-storybook-with-composition",
  "/recipes/storybook/custom-builder-configs": "/technologies/test-tools/storybook/recipes/custom-builder-configs",
  "/recipes/storybook/storybook-interaction-tests": "/technologies/test-tools/storybook/recipes/storybook-interaction-tests",
  "/recipes/storybook/upgrading-storybook": "/technologies/test-tools/storybook/recipes/upgrading-storybook",
  "/recipes/storybook/storybook-composition-setup": "/technologies/test-tools/storybook/recipes/storybook-composition-setup",
  "/recipes/storybook/angular-storybook-compodoc": "/technologies/test-tools/storybook/recipes/angular-storybook-compodoc",
  "/recipes/storybook/angular-configuring-styles": "/technologies/test-tools/storybook/recipes/angular-configuring-styles",
  "/recipes/cypress": "/technologies/test-tools/cypress",
  "/recipes/cypress/cypress-component-testing": "/technologies/test-tools/cypress/recipes/cypress-component-testing",
  "/recipes/cypress/cypress-setup-node-events": "/technologies/test-tools/cypress/recipes/cypress-setup-node-events",
  "/recipes/cypress/cypress-v11-migration": "/technologies/test-tools/cypress/recipes/cypress-v11-migration",
  "/recipes/next": "/technologies/react/next",
  "/recipes/next/next-config-setup": "/technologies/react/next/recipes/next-config-setup",
  "/recipes/nuxt": "/technologies/vue/nuxt",
  "/recipes/nuxt/deploy-nuxt-to-vercel": "/technologies/vue/nuxt/recipes/deploy-nuxt-to-vercel",
  "/recipes/vite": "/technologies/build-tools/vite",
  "/recipes/vite/configure-vite": "/technologies/build-tools/vite/recipes/configure-vite",
  "/recipes/webpack": "/technologies/build-tools/webpack",
  "/recipes/webpack/webpack-config-setup": "/technologies/build-tools/webpack/recipes/webpack-config-setup",
  "/recipes/webpack/webpack-plugins": "/technologies/build-tools/webpack/recipes/webpack-plugins",
  "/recipes/tips-n-tricks/eslint": "/technologies/eslint",
  "/recipes/tips-n-tricks/switch-to-workspaces-project-references": "/technologies/typescript/recipes/switch-to-workspaces-project-references",
  "/recipes/tips-n-tricks/enable-tsc-batch-mode": "/technologies/typescript/recipes/enable-tsc-batch-mode",
  "/recipes/tips-n-tricks/define-secondary-entrypoints": "/technologies/typescript/recipes/define-secondary-entrypoints",
  "/recipes/tips-n-tricks/compile-multiple-formats": "/technologies/typescript/recipes/compile-multiple-formats",
  "/recipes/tips-n-tricks/js-and-ts": "/technologies/typescript/recipes/js-and-ts",
  "/recipes/tips-n-tricks/flat-config": "/technologies/eslint/recipes/flat-config"
};

module.exports = { nxRecipesRedirects };
